FROM node:16 

WORKDIR  /app

COPY package*.json /app  

COPY . /app

ENV GOOGLE_CLIENT_ID="$AAA_SECRET_TEXT.$GOOGLE_CLIENT_ID"
ENV GOOGLE_CLIENT_SECRET="$AAA_SECRET_TEXT.$GOOGLE_CLIENT_SECRET"
ENV GOOGLE_CALLBACK="$AAA_SECRET_TEXT.$GOOGLE_CALLBACK"
ENV GOOGLE_REFRESH_TOKEN="$AAA_SECRET_TEXT.$GOOGLE_REFRESH_TOKEN"
ENV DOMAIN="$AAA_SECRET_TEXT.$DOMAIN"
ENV travisApiToken="$AAA_SECRET_TEXT.$travisApiToken"
ENV squareApplicationId="$AAA_SECRET_TEXT.$squareApplicationId"
ENV SQUARE_TOKEN="$AAA_SECRET_TEXT.$SQUARE_TOKEN"
ENV squareBasePath="$AAA_SECRET_TEXT.$squareBasePath"
ENV SQUARE_LOCATION_ID="$AAA_SECRET_TEXT.$SQUARE_LOCATION_ID"
ENV Kubernetes_Cluster_DB="$AAA_SECRET_TEXT.$Kubernetes_Cluster_DB"


RUN npm i 

CMD npm run start-prod
